// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
<<<<<<< HEAD
      return web;
=======
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
>>>>>>> 03ac4ae0061350d445124e0c9663c0ea7e14109b
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
<<<<<<< HEAD
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
=======
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
>>>>>>> 03ac4ae0061350d445124e0c9663c0ea7e14109b
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

<<<<<<< HEAD
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1krnizLdaPfw-INv5ReTrt7QWVhUNXqs',
    appId: '1:351408659635:web:83718678cd6fcb3a92a4c6',
    messagingSenderId: '351408659635',
    projectId: 'travelapp-e464f',
    authDomain: 'travelapp-e464f.firebaseapp.com',
    storageBucket: 'travelapp-e464f.firebasestorage.app',
    measurementId: 'G-777TKBSZS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrTB9k9BsBbsY96Yjcub3WE0LEMcMgV4s',
    appId: '1:351408659635:android:b2982ebd578896a492a4c6',
    messagingSenderId: '351408659635',
    projectId: 'travelapp-e464f',
    storageBucket: 'travelapp-e464f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe9ei5etkwfbynXSRk6Idg2CMs4YzK8fc',
    appId: '1:351408659635:ios:714b02ed1a0497bc92a4c6',
    messagingSenderId: '351408659635',
    projectId: 'travelapp-e464f',
    storageBucket: 'travelapp-e464f.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe9ei5etkwfbynXSRk6Idg2CMs4YzK8fc',
    appId: '1:351408659635:ios:714b02ed1a0497bc92a4c6',
    messagingSenderId: '351408659635',
    projectId: 'travelapp-e464f',
    storageBucket: 'travelapp-e464f.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1krnizLdaPfw-INv5ReTrt7QWVhUNXqs',
    appId: '1:351408659635:web:dcb4c09d5cbc34b992a4c6',
    messagingSenderId: '351408659635',
    projectId: 'travelapp-e464f',
    authDomain: 'travelapp-e464f.firebaseapp.com',
    storageBucket: 'travelapp-e464f.firebasestorage.app',
    measurementId: 'G-9K70PP3F8M',
  );

}
=======
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsNvUfgGKOTJEZnRgJESrEf_Pv5vfItCw',
    appId: '1:436614213200:android:dcd404468938d569f26b55',
    messagingSenderId: '436614213200',
    projectId: 'app-travel-64d25',
    storageBucket: 'app-travel-64d25.firebasestorage.app',
  );
}
>>>>>>> 03ac4ae0061350d445124e0c9663c0ea7e14109b
